### PR TITLE
fix(textarea): properly adjust auto-grow textarea height on scrolled content

### LINKED ISSUE #19193: bug: ion-textarea autoGrow scroll to top on input
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
ionic textarea with autoGrow, scrolls to top on input, when user's input excedes screen height.

**Expected behavior:**
ionic textarea with autoGrow must scroll to key input position,

**Steps to reproduce:**
create a new project, add ion textarea with autogrow attribute and insert text

**Related code:**
Ionic Angular StackBlitz: https://stackblitz.com/edit/ionic-v4-angular-autogrow-error

```
    <ion-textarea
      [autoGrow]="true"
      placeholder="test">
    </ion-textarea>
```

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

System:

   NodeJS : v12.9.1 (/usr/local/bin/node)
   npm    : 6.10.2
   OS     : Linux 4.18
```

### PR DESCRIPTION
**Pull request by haydenbr**
Remove setting the nativeInput height to 'initial' before resetting it to scrollHeight in Textarea.runAutoGrow

closes #19193

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: #19193

## What is the new behavior?

When adding text into an autoGrow textarea, the browser window (or scroll element) is no longer automatically scrolled to the top of the textarea

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

As far as I know, this doesn't introduce any breaking change. I wasn't sure how to add automated tests for this, but I'd be happy to take care of it if someone were able to point me in the right direction.

The function that I changed had the following comment above it: `// TODO: performance hit, this cause layout thrashing` so apparently this is a known issue, at least to someone.

Debugging locally, removing the single line `nativeInput.style.height = 'inherit'` before updating the element height to the scroll height fixed the problem. This seems to easy though, so maybe Im missing something? I wasn't sure why the height was being set to `'inherit'` in the first place.

# Update

This PR has since been updated with a proper fix, which is reflected in the current state of the commit for this PR. See [this comment](https://github.com/ionic-team/ionic/pull/19776#issuecomment-559210927) below.

I ran a git blame and this was the output:
```
3cdab10aa0 core/src/components/textarea/textarea.tsx          (Brandy Carney      2019-04-24 12:33:22 -0400 193)
26e6d6f115 core/src/components/textarea/textarea.tsx          (Manu MA            2019-07-17 19:23:13 +0200 194)   // TODO: performance hit, this cause layout thrashing
cc8678ad58 core/src/components/textarea/textarea.tsx          (Adam LaCombe       2019-05-07 16:52:24 -0400 195)   private runAutoGrow() {
34dfc3ce98 core/src/components/textarea/textarea.tsx          (Manu MA            2019-06-23 11:26:42 +0200 196)     const nativeInput = this.nativeInput;
34dfc3ce98 core/src/components/textarea/textarea.tsx          (Manu MA            2019-06-23 11:26:42 +0200 197)     if (nativeInput && this.autoGrow) {
34dfc3ce98 core/src/components/textarea/textarea.tsx          (Manu MA            2019-06-23 11:26:42 +0200 198)       readTask(() => {
26e6d6f115 core/src/components/textarea/textarea.tsx          (Manu MA            2019-07-17 19:23:13 +0200 199)         nativeInput.style.height = 'inherit';
34dfc3ce98 core/src/components/textarea/textarea.tsx          (Manu MA            2019-06-23 11:26:42 +0200 200)         nativeInput.style.height = nativeInput.scrollHeight + 'px';
34dfc3ce98 core/src/components/textarea/textarea.tsx          (Manu MA            2019-06-23 11:26:42 +0200 201)       });
cc8678ad58 core/src/components/textarea/textarea.tsx          (Adam LaCombe       2019-05-07 16:52:24 -0400 202)     }
cc8678ad58 core/src/components/textarea/textarea.tsx          (Adam LaCombe       2019-05-07 16:52:24 -0400 203)   }
```

### CODE REVIEW

**Comment by haydenbr** [comment]
Hmm ok. Never mind. I see why `style.height = 'inherit'` is there: to reset the textarea's height in case the user removes text.

**Comment by roxteddy** [comment]
Hello @haydenbr 

> to reset the textarea's height in case the user removes text.

Couldn't you check nativeInput.textLength before updating nativeInput.style.height whether with inherit or scrollHeight ?

Also, can you confirm removing nativeInput.style.height = 'inherit' solve the scrolling to problem problem ?

**Comment by haydenbr** [comment]
Hey @roxteddy 

As far as I know, textLength is only an attribute available on some elements related to SVGs ([source](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/textLength)).

Removing `nativeInput.style.height = 'inherit'` is a temporary tradeoff. It does fix the top scrolling problem, but introduces a lesser problem in that when removing text from the textarea, the textarea does not strink back down to the appropriate size.

**Comment by roxteddy** [comment]
@haydenbr

`<ion-textarea auto-grow="true"
                              (ionInput)="onTextInput($event)"
                </ion-textarea>`

`onTextInput(event) {
        event.target.getInputElement().then((textArea: HTMLTextAreaElement) => {
           console.log(textArea.textLength + " : " + textArea.value);
           textArea.scroll({top: textArea.scrollHeight});
        });
    }`

> 1 : q
> 2 : qw
> 3 : qwe
> 4 : qwer
> 5 : qwert
> 6 : qwerty

**Comment by haydenbr** [comment]
@roxteddy

The scrolling looks like a nice workaround. I'll have to give it a try.

I didn't know textarea had a textLength, although that still only gives the string length of textarea.value

**Comment by haydenbr** [comment]
Hi @brandyscarney!

Sorry this took so long, but I just wanted to give you a heads up that I implemented a fix for this issue. It ended up being a very simple fix.

Essentially, I wrap the textarea in a div whose height is updated to the textarea's `scrollHeight`, after the textarea's height is reset. Doing this prevent's the component's height from shrinking to zero when it's height is set to `'auto'`, which is what was causing the entire screen to "jump" to the top of the textarea.

I also wanted to ask what kind of tests should be included to cover this, since this is more of a visual issue. The existing tests passed, but I don't know if that's good enough for you all to accept this or if you have a recommendation for what I could do for testing.

Thanks in advance for your time. I look forward to any feedback you all might have on this, and thanks for all your great work in building ionic.

**Comment by WildSunLove** [comment]
Thank you for this! Excited for this to be merged in, we just had this come up with our newly released app and it's great to see a fix is almost in place

**Comment by haydenbr** [comment]
Hey, I know you all are super busy, but I just wanted to see if there's been any progress on reviewing this.

**Comment by haydenbr** [comment]
@brandyscarney @manucorporat I'm really sorry for commenting at you all directly. I know you and the team must be very busy, especially with v5 just coming out, but I was wondering if it would be possible for anyone to review this PR anytime in the near future?

This defect still exists in v5, and this PR introduces a very small change to fix it.

updated reproduction to v5 -> https://github.com/ionic-team/ionic/issues/19193#issuecomment-547099641

File: core/src/components/textarea/textarea.tsx [hunk 1]
```diff
@@ -310,29 +313,31 @@ export class Textarea implements ComponentInterface {
...
-          rows={this.rows}
-          wrap={this.wrap}
-          onInput={this.onInput}
-          onBlur={this.onBlur}
-          onFocus={this.onFocus}
-          onKeyDown={this.onKeyDown}
-        >
-          {value}
-        </textarea>
+        <div class="textarea-wrapper">
```
Comment (haydenbr) [inline core/src/components/textarea/textarea.tsx]: This was the only change to the component template. All of the props remain as is.

**Comment by haydenbr** [comment]
I can't seem to get anyone to review it, even though this was a known issue ¯\_(ツ)_/¯

File: core/src/components/textarea/textarea.tsx (hunk 1 above)
Comment (liamdebeasi) [inline core/src/components/textarea/textarea.tsx]: Can we add a ref here instead of doing a `querySelector` every time we run autogrow?

```suggestion
        <div class="textarea-wrapper"
          ref={el => this.textareaWrapper = el}
        >
```

Then instead of doing `const inputContainer = this.el.querySelector<HTMLElement>('.textarea-wrapper');` you can just do `const inputContainer = this.textareaWrapper`

**Comment by liamdebeasi** [comment]
Other than the change I requested in https://github.com/ionic-team/ionic/pull/19776#discussion_r396621291, this PR should be good to go.

**Comment by haydenbr** [comment]
@liamdebeasi Thanks so much for reviewing this and for calling out the suggestion about not re-running the querySelector.

**Comment by haydenbr** [comment]
I'll take care of this by the end of the day. Thanks!

**Comment by haydenbr** [comment]
@liamdebeasi Looks like the build is failing on build-react-router 🤔. Should I rebase my changes onto the most recent version of master?

**Comment by liamdebeasi** [comment]
Merged. Thank you!

**Comment by jonmbennett** [comment]
Beginning in 5.0.6, this change seems to cause a noticeable input delay when switching between different text areas on the same form. In my tests it only seems to affect iOS, not Android.

Perhaps this is what the `// TODO: performance hit, this cause layout thrashing` comment was referring to. It affects all text-areas, even if auto-grow is set to false.

**Comment by liamdebeasi** [comment]
@jonmbennett That is a different bug that will be fixed in an upcoming release of Ionic Framework.

**Comment by mobileias** [comment]
@liamdebeasi 
hello 
we are facing issue with ion-item and ion-input 
if we use ion-input with ion-item then keyboard accessory bar button never works, so can you please help me to solve that issue ?
we are using latest ionic/angular 5.1.0 also but still same issue sir.

Thanks in advance Sir!

**Comment by liamdebeasi** [comment]
@mobileias Please see https://github.com/ionic-team/ionic/issues/16498#issuecomment-557246893

**Comment by mobileias** [comment]
@liamdebeasi 
ok thanks, we also watch that

**Comment by t4tapas** [comment]
My Ionic version is 6.16.1 and I am still facing the exact issue [https://github.com/ionic-team/ionic-framework/issues/19193](url).
