### PR TITLE
fix(react): handle undefined attributes better, fixes #19563, #19580

### LINKED ISSUE #19563: bug: React IonRange is disabled even if `disabled === undefined`
# Bug Report

**Ionic version:**
"@ionic/core": "^4.10.0",
"@ionic/react": "^4.10.0-rc.3",

**Current behavior:**

Having `IonRange` component and it's prop `disabled` to which I pass variable that can be `type boolean | undefined`,
-> when the variable is equal to `false` IonRange is **enabled**
-> when the variable is equal to `true` IonRange is **disabled**
-> when the variable is equal to `undefined` IonRange is **enabled**

**Expected behavior:**

Having `IonRange` component and it's prop `disabled` to which I pass variable that can be `type boolean | undefined`,
-> when the variable is equal to `false` IonRange have to be  **enabled**
-> when the variable is equal to `true` IonRange have to be **disabled**
-> when the variable is equal to `undefined` IonRange have to be **disabled** because `undefined` is a falsy value

**Steps to reproduce:**

**Related code:**
```JSX
<div className={rangeModifier(urgencyIndex)}>
      <IonRange
        disabled={readOnly}
        max={urgency && urgency.size}
        min={1}
        mode='ios'
        onIonChange={onChange}
        snaps
        step={1}
        value={urgencyIndex}
      />
    </div>
```

### PR DESCRIPTION
**Pull request by elylucas**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: #19563, #19580

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

File: packages/react/src/components/utils/attachEventProps.ts [hunk 1]
```diff
@@ -19,7 +19,8 @@ export const attachEventProps = (node: HTMLElement, newProps: any, oldProps: any
         syncEvent(node, eventNameLc, newProps[name]);
       }
     } else {
-      if (typeof newProps[name] === 'object') {
+      const propType = typeof newProps[name];
+      if (propType === 'object' || propType === 'undefined') {
         (node as any)[name] = newProps[name];
       } else {
         node.setAttribute(camelToDashCase(name), newProps[name]);
```
Comment (manucorporat) [inline packages/react/src/components/utils/attachEventProps.ts]: Do we need to setAttribute at all? convert a prop name to dash case might not  work, we should always set property:
```
if (name in node) {
    node[name] = newProps[name];
}
```

Also, if our code adds attributes, we need to also add code to  remove them (I don't think we should do that at all), we should use properties 99%  of the times. In fact, we remove pure CSS attributes for this reason, also JSX  will complain about any non-prop passed

Comment (manucorporat) [reply packages/react/src/components/utils/attachEventProps.ts]: On a side note, why is this function called `attachEventProps` seems like it's doing a lot more than that

**Comment by SatoAV** [comment]
Should this PR also fix this issue?
https://github.com/ionic-team/ionic/issues/19546

Very much hoping it does :)
