### PR TITLE
fix(textarea): set correct height in a modal when auto-grow is set

### LINKED ISSUE #18993: bug: ion-textarea autoGrow=“true” on modal, work only the first time
**Expected behaviour:**
Each time the ion-textarea should be the same size.

**Actual behaviour:**
I have a strange behaviour with ion-textarea autoGrow="true" that was introduced in ionic 4.4, the first time the autoGrow is made correctly. The 2nd time the textarea is less than 1 row. We can't even see the text. This bug is only on "modal".

I open the modal like this

 ```
displayModal(data) {
this.modalCtrl.create({
  component: EventDetailModalComponent, componentProps: {
    event: data.appointmentData,
    timeFormat: this.timeFormat,
    dateFormat: this.dateFormat
  }
}).then(modalElement => {
  modalElement.present();
});  }
```
And close like this :

   `onCancel() { this.modalCtrl.dismiss(); }`
View contains :

```
 <ion-item lines="none">
        <ion-label position="floating">{{'DESCRIPTION' | translate }}</ion-label>
        <ion-textarea readonly disabled autoGrow="true" class="ion-text-justify" value="{{ description }}" ></ion-textarea>
 </ion-item>
```
For info, the text is inserted manually by the programme in value="x", not entered by the user.

I'm running the last version of ionic ("@ionic-native/core": "^5.11.0") and Angular (8.2).
Same problem tested on last version of Chrome, Safari and FireFox on Mac.

You can test here : 
https://stackblitz.com/edit/ionic-v4-angular-ion-textarea-autogrowth

This was already reported on "stackoverflow":
https://stackoverflow.com/questions/57336796/ion-textarea-autogrow-true-on-modal-work-only-the-first-time
They came to the conclusion that should be a bug.

### PR DESCRIPTION
**Pull request by acurrieclark**
Fixes #18993

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
When an `ion-textarea` element with `auto-grow="true"` is used within an `ion-modal`, it is shown correctly on the first load, but each subsequent load of the modal results in a `textarea` element height of 0.

Issue Number: #18993

## What is the new behavior?
The `textarea` now loads with the correct height on subsequent loads of the modal

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I went to add tests for this and realised that the problem is not present when used in a pure javascript project. I first saw the issue in an `@ionic/angular` project. I have tested this with a locally linked build of `@ionic/core` and this solves the problem.

### CODE REVIEW

File: core/src/components/textarea/textarea.tsx [hunk 1]
```diff
@@ -189,7 +189,9 @@ export class Textarea implements ComponentInterface {
   }
 
   componentDidLoad() {
-    this.runAutoGrow();
+    setTimeout(() => {
+      this.runAutoGrow();
+    });
```
Comment (liamdebeasi) [inline core/src/components/textarea/textarea.tsx:194]:
```suggestion
    raf(() => this.runAutoGrow());
```

Let's use the `raf` helper instead. This will use `requestAnimationFrame` instead of `setTimeout` and will also avoid NgZone being run.

You can modify the import line at the top of the file: 

`import { debounceEvent, findItemLabel, raf } from '../../utils/helpers';`

Comment (acurrieclark) [reply core/src/components/textarea/textarea.tsx]: Thanks for the feedback. Changes made!

**Comment by acurrieclark** [comment]
Tested the changes in an angular app and all functions as expected

**Comment by liamdebeasi** [comment]
Merged. Thank you!

**Comment by acurrieclark** [comment]
Most welcome. Thanks very much

File: core/src/components/textarea/textarea.tsx (hunk 1 above)
Comment (am5815) [reply core/src/components/textarea/textarea.tsx]: Hi Guys, I have a project where I am getting this problem. How do I implement this fix?

Comment (acurrieclark) [reply core/src/components/textarea/textarea.tsx]: This has been merged and is in the current 5.1.0 release

**Comment by giuseppe987** [comment]
Hi! It isn't working on react.

**Comment by giuseppe987** [comment]
> Hi! It isn't working on react.

I fix it setting a min-height in child elements. Maybe it helps just for now.

**Comment by giuseppe987** [comment]
The fix that worked for me.

	useEffect(() => {
		setTimeout(() => {
			if (ionTextareaRef.current) {
				const ionTextareaRef_Div = ionTextareaRef.current.querySelector("div")
				const ionTextareaRef_Div_Textarea = ionTextareaRef.current.querySelector(
					"textarea"
				)
				if (ionTextareaRef_Div && ionTextareaRef_Div_Textarea) {
					ionTextareaRef_Div.style.height =
						ionTextareaRef_Div_Textarea.scrollHeight + "px"
					ionTextareaRef_Div_Textarea.style.height =
						ionTextareaRef_Div_Textarea.scrollHeight + "px"
				}
			}
		}, 700)
	}, [])

**Comment by Lxstr** [comment]
I'm encountering this exact issue with stenciljs and ionic 5.5. Any ideas why it might be present?

**Comment by leetmike** [comment]
> I'm encountering this exact issue with stenciljs and ionic 5.5. Any ideas why it might be present?
Try rows="1" I was encountering the same behavior and doing this fixed it... Using Angular 12 / Ionic 5.5.

**Comment by ipehimanshu** [comment]
yes true that is still present into latest version also
image

**Comment by laocker96** [comment]
> The fix that worked for me.
> 
> ```
> useEffect(() => {
> 	setTimeout(() => {
> 		if (ionTextareaRef.current) {
> 			const ionTextareaRef_Div = ionTextareaRef.current.querySelector("div")
> 			const ionTextareaRef_Div_Textarea = ionTextareaRef.current.querySelector(
> 				"textarea"
> 			)
> 			if (ionTextareaRef_Div && ionTextareaRef_Div_Textarea) {
> 				ionTextareaRef_Div.style.height =
> 					ionTextareaRef_Div_Textarea.scrollHeight + "px"
> 				ionTextareaRef_Div_Textarea.style.height =
> 					ionTextareaRef_Div_Textarea.scrollHeight + "px"
> 			}
> 		}
> 	}, 700)
> }, [])
> ```

Hi @giuseppe987  can you pls post more source code ?

**Comment by laocker96** [comment]
I could have found a solution. Posting in 2 days if testing is good.

**Comment by Lxstr** [comment]
I think this has now been fixed in ionic 6 as per this https://github.com/ionic-team/ionic-framework/issues/21242. Can you check what happens when you update to ionic 6?

**Comment by luongtu996** [comment]
it is ok in ionic6
