### PR TITLE
fix(item): do not disable entire item if there are multiple inputs

### LINKED ISSUE #18670: bug: ion-item > inputs are all disabled if a child of ion-item is
# Bug Report

**Ionic version:**

[x] **4.6**

**Current behavior:**
Let's pretend a `ion-item` have some input childs like `ion-checkbox` or `ion-input`. If one of the child input is `[disabled]="true"`, the whole `ion-item` is disabled too.

**Expected behavior:**
The parent *should not* be responsable for child disability.

**Steps to reproduce:**
Just have a `ion-item` with some child inputs.

**Related code:**

```
<ion-item>
    <ion-checkbox [disabled]="true"></ion-checkbox>
    <ion-input type="text" [disabled]="false"></ion-input>
</ion-item>
```
One of the child is disabled, so `ion-item` is disabled too.

**Other information:**
I used this workaround to keep the `ion-item` "not disabled".

```
ion-content {
  ion-item {
    pointer-events: auto;
  }
}
```
It seems like the `.item-interactive-disabled ` class is responsible for this behavior.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.1
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.800.6
   @angular-devkit/schematics    : 8.0.6
   @angular/cli                  : 8.0.6
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 7 other plugins)

Utility:

   cordova-res : 0.3.0 (update available: 0.5.1)
   native-run  : not installed

System:

   NodeJS : v11.14.0 (/usr/bin/node)
   npm    : 6.9.2
   OS     : Linux 5.0
```

### PR DESCRIPTION
**Pull request by brandyscarney**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
View the following Codepen to see the behavior on 4.5.0: https://codepen.io/brandyscarney/pen/KjRqRB

Change the assets to `4.6.0` to see the broken behavior.

Issue Number: fixes #18670

## What is the new behavior?

- View the new behavior at the following tests
  - `http://localhost:3333/src/components/item/test/disabled`
  - `http://localhost:3333/src/themes/test/css-variables`
- Any of the individual input tests (radio, checkbox, toggle, datetime, select, etc.)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: core/src/components/item/item.tsx [hunk 1]
```diff
@@ -128,20 +128,30 @@ export class Item implements ComponentInterface, AnchorInterface, ButtonInterfac
...
-    // Check for multiple inputs to change the position to relative
-    const inputs = this.el.querySelectorAll('ion-select, ion-datetime');
-    this.multipleInputs = inputs.length > 1 ? true : false;
+    // The following elements have a clickable cover that is relative to the entire item
+    const covers = this.el.querySelectorAll('ion-checkbox, ion-datetime, ion-select, ion-radio');
+
+    // The following elements can accept focus alongside the previous elements
+    // therefore if these elements are also a child of item, we don't want the
+    // input cover on top of those interfering with their clicks
+    const inputs = this.el.querySelectorAll('ion-input, ion-range, ion-textarea, ion-toggle');
```
Comment (liamdebeasi) [inline core/src/components/item/item.tsx]: We might need `ion-searchbar` here
```suggestion
    const inputs = this.el.querySelectorAll('ion-input, ion-range, ion-textarea, ion-toggle, ion-searchbar');
```

Comment (liamdebeasi) [reply core/src/components/item/item.tsx]: also noticing this breaks if a user uses `ion-segment`. It's not technically an input, but maybe we can put a check for it somewhere?
