### PR TITLE
fix(global): Only cascade mode from parent *Ionic* components

### LINKED ISSUE #20055: bug: Setting [mode]=" 'not ios or md' " causes './undefined.entry.js' Error
# Bug Report

**Ionic version:**

[x] 5.0.0-beta.1

**Current behavior:**

Set an invalid value for any [mode] flag. The following error occurs.

````
core-9d3f3c18.js:63 Error: Cannot find module './undefined.entry.js'
    at .*\.entry\.js$ include: \.entry\.js$ exclude: \.system\.entry\.js$ namespace object:385
    at ZoneDelegate.invoke (zone-evergreen.js:359)
    at Zone.run (zone-evergreen.js:124)
    at zone-evergreen.js:855
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)
consoleError @ core-9d3f3c18.js:63
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:855
invokeTask @ zone-evergreen.js:391
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:559
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:542
scheduleTask @ zone-evergreen.js:381
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:372
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:845
resolvePromise @ zone-evergreen.js:791
(anonymous) @ zone-evergreen.js:707
webpackJsonpCallback @ bootstrap:25
(anonymous) @ tab1-tab1-module.js:13


zone-evergreen.js:651 Unhandled Promise rejection: Cannot read property 'isProxied' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'isProxied' of undefined
    at initializeComponent (core-9d3f3c18.js:1737) TypeError: Cannot read property 'isProxied' of undefined
    at initializeComponent (http://localhost:8101/vendor.js:105947:24)
````

**Expected behavior:**

An error should be displayed that tells the user where to find the issue in question. Right now it is virtually impossible to track this down unless you know what you are doing. I only found it by deleting code until the error went away, then adding it back, and so on, until I was able to pinpoint the problem.

**Steps to reproduce:**

1. ionic start myApp tabs
2. Edit tab1.page.html and add `mode=foo` to any `ion-item` component.
3. Reload page.. kapow.

**Related code:**

```

      <ion-item href="https://ionicframework.com/docs/" mode=foo>
        <ion-icon slot="start" color="medium" name="book"></ion-icon>
        <ion-label>Ionic Documentation</ion-label>
      </ion-item>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.10 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.0-beta.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.0 (/usr/local/lib/node_modules/node/bin/node)
   npm    : 6.13.1
   OS     : macOS Catalina

```

### PR DESCRIPTION
**Pull request by jakobe**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: Fixes #20055 

Wrapping an Ionic component in a non-Ionic element with a `mode` attribute throws error:

```html
<p mode="foo">
  <ion-label></ion-label>
</p>
```

## What is the new behavior?

Only apply the Ionic mode from Ionic ancestors.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

File: core/src/global/ionic-global.ts [hunk 1]
```diff
@@ -49,11 +49,17 @@ export default () => {
...
+
+  const isAllowedIonicModeValue = (elmMode: string) =>
+      ['ios', 'md'].includes(elmMode);
+
   setMode((elm: any) => {
     while (elm) {
       const elmMode = (elm as any).mode || elm.getAttribute('mode');
 
-      if (elmMode) {
+      if (elmMode && (isIonicElement(elm) || isAllowedIonicModeValue(elmMode))) {
```
Comment (kensodemann) [inline core/src/global/ionic-global.ts]: Discussed with the FW team. They believe this would really be useful if it did something like the following completely untested code:

```typescript
  setMode((elm: any) => {
    while (elm) {
      const elmMode = (elm as any).mode || elm.getAttribute('mode');
      if (elmMode) {
        if (isAllowedIonicModeValue(elmMode)) {
          return elmMode;
        } else if (isIonicElement(elmMode)) {
          console.warn('Invalid ionic mode:', elmMode, 'expected: ios or md');
        }
      }
      elm = elm.parentElement;
    }
    return defaultMode;
  });
};
```

That way the user would be warned about the invalid mode on an Ionic element and the code would keep going up the tree rather than failing on that.

Would you be willing to make such a change?

Comment (brandyscarney) [reply core/src/global/ionic-global.ts]: I did this. 🙂

File: core/src/global/ionic-global.ts [hunk 2]
```diff
@@ -49,14 +49,22 @@ export default () => {
...
+
   setMode((elm: any) => {
     while (elm) {
       const elmMode = (elm as any).mode || elm.getAttribute('mode');
-
       if (elmMode) {
-        return elmMode;
+        if (isAllowedIonicModeValue(elmMode)) {
+          return elmMode;
+        } else if (isIonicElement(elmMode)) {
```
Comment (kensodemann) [inline core/src/global/ionic-global.ts]: Shouldn't that be "elm" that is passed there? (the element, not the mode)

**Comment by jakobe** [comment]
Great! The final changes looks great 👍

**Comment by brandyscarney** [comment]
This will be in the `5.0.6` release we're releasing in a bit. Thanks again. 🙂
