### PR TITLE
fix(item-option): add styling for slots other than icon-only

### LINKED ISSUE #17402: [Ionic v4] (ion-item-option + routerlink) > ion-icon  => icon displays too low
**Ionic info:** 
```
   ionic (Ionic CLI)             : 4.8.0
   Ionic Framework               : @ionic/angular 4.0.0-rc.1
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

System:

   NodeJS : v8.12.0
   npm    : 6.4.1
   OS     : Linux 4.15
```

# Bug Report

**Ionic version:**
[x] **4.8.0**

**Current behavior:**
The icon misaligns and is displayed too low when an ion-item-option is used with a routerLink

**Expected behavior:**
Aligned icons

**Steps to reproduce:**
1 - Run a sample of code using the related code
2 - Slide the item using the routerLink

**Related code:**
``` html
<ion-content>
  <ion-list no-border #slidingList>

    <ion-list-header>
      TODOLIST
    </ion-list-header>
    
    <ion-item-sliding *ngFor="let tdl of todolists">

      <ion-item [routerLink]="'/list-items/'+ tdl.uuid" routerDirection="forward">
        <ion-label>{{tdl.name}}</ion-label>
        <p item-end>{{tdl.items.length}}</p>
      </ion-item>

      <ion-item-options side="end">
        <ion-item-option color="danger" (click)=delete(tdl.uuid,tdl.name)>
          <ion-icon slot="icon-only" name="trash"></ion-icon>
        </ion-item-option>

<-- This item-option does not display its icon the correct way -->
        <ion-item-option [routerLink]="'/editlist/' + tdl.uuid" routerDirection="forward" color="primary" (click)=resetList()>
          <ion-icon slot="icon-only" name="create"></ion-icon>
        </ion-item-option>
<-- -->
      </ion-item-options>
    
    </ion-item-sliding>

  </ion-list>
</ion-content>`
```
  
bugionic
  
**Working solution**  
Remove "[routerLink]="..." routerDirection="..." corrects the bug

### LINKED ISSUE #17737: bug: item sliding options are not applying layout properly
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Slotted items in an item option are not styling properly.

**Expected behavior:**
If the slot is top or bottom the item should be on top of or below the label

**Steps to reproduce:**
See the following Codepen, open the "top" and "bottom" layout items: https://codepen.io/brandyscarney/pen/VRWLOd?editors=1000

**Related code:**

Example of one that doesn't work:

```
  <ion-item-sliding>
    <ion-item>
      <ion-label>
        Sliding Item, Icons Bottom
      </ion-label>
    </ion-item>
    <ion-item-options>
      <ion-item-option color="primary">
        <ion-icon slot="bottom" name="more"></ion-icon>
        More
      </ion-item-option>
      <ion-item-option color="secondary">
        <ion-icon slot="bottom" name="archive"></ion-icon>
        Archive
      </ion-item-option>
    </ion-item-options>
  </ion-item-sliding>
```

**Ionic info:**
```
master
```

### PR DESCRIPTION
**Pull request by brandyscarney**
Styles the item option properly when icons are slotted. This was not working before at all for `top` and `bottom` slots.

Also:

- removes the e2e test from item/sliding in favor of all of them being under item-sliding
- adds more usage examples for all framewroks
- updates the styling for an anchor option so that it displays properly
- updates the standalone e2e test to take screenshots of the start icon, top icon, and anchor options
- updates the interactive e2e test to work locally
- cleaned up the CSS for start/end icons
- verified the styles for ben approval :muscle:

Screen Shot 2019-03-11 at 1 20 08 PM

closes #17737 fixes #17402

### CODE REVIEW

File: core/src/components/item-sliding/test/standalone/e2e.ts [hunk 1]
```diff
@@ -5,6 +5,45 @@ test('item-sliding: standalone', async () => {
...
+  await openItem(item, page);
+
+  compares.push(await page.compareScreenshot());
+
+  for (const compare of compares) {
+    expect(compare).toMatchScreenshot();
+  }
 });
+
+async function openItem(item: any, page: any) {
```
Comment (liamdebeasi) [inline core/src/components/item-sliding/test/standalone/e2e.ts]: Can we move this to something a `test.utils.ts` file in `item-sliding/test`? 

That way we can have `openItem` and `deleteItem` functions and the tests in `tests/interactive` can call these functions as well.

Comment (brandyscarney) [reply core/src/components/item-sliding/test/standalone/e2e.ts]: yeah sure if I can ever get screenshot to run :joy:

**Comment by brandyscarney** [comment]
Good to merge once the build passes 👍
