### PR TITLE
fix(css): update deprecations to remove wrap

### LINKED ISSUE #19499: bug: False positive on CSS deprecation warning
# Bug Report

**Ionic version:**
[x] **4.10.0**

**Current behavior:**
Deprecation warning for CSS attributes generates false positive when using:
`<ion-textarea wrap="soft"></ion-textarea>`

**Expected behavior:**
Should ignore attributes with an assigned value.

**Steps to reproduce:**
Create an empty page with the above ion-textarea code. See warning appear in the console.

**Related code:**
See above.

**Other information:**

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\cpollard\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.803.6
   @angular-devkit/schematics    : 8.3.6
   @angular/cli                  : 8.3.6
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic 5.4.4, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 16 other plugins)

Utility:

   cordova-res : 0.3.0 
   native-run  : 0.2.2

System:

   Android SDK Tools : 26.1.1 (C:\Users\cpollard\AppData\Local\Android\Sdk)
   NodeJS            : v12.11.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.11.3
   OS                : Windows 10
```

### PR DESCRIPTION
**Pull request by brandyscarney**
the wrap attribute is still deprecated from global CSS but it improperly throws errors on textarea where it's valid

fixes #19499

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

File: angular/src/directives/css-utils-deprecations.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
...
...stify], [text-start], [text-end], [text-left], [text-right], [text-nowrap], [text-wrap], [text-sm-center], [text-sm-justify], [text-sm-start], [text-sm-end], [text-sm-left], [text-sm-right], [text-sm-nowrap], [text-sm-wrap], [text-md-center], [text-md-justify], [text-md-start], [text-md-end], [text-md-left], [text-md-right], [text-md-nowrap], [text-md-wrap], [text-lg-center], [text-lg-justify], [text-lg-start], [text-lg-end], [text-lg-left], [text-lg-right], [text-lg-nowrap], [text-lg-wrap], [text-xl-center], [text-xl-justify], [text-xl-start], [text-xl-end], [text-xl-left], [text-xl-right], [text-xl-nowrap], [text-xl-wrap], [text-uppercase], [text-lowercase], [text-capitalize], [text-sm-uppercase], [text-sm-lowercase], [text-sm-capitalize], [text-md-uppercase], [text-md-lowercase], [text-md-capitalize], [text-lg-uppercase], [text-lg-lowercase], [text-lg-capitalize], [text-xl-uppercase], [text-xl-lowercase], [text-xl-capitalize], [no-padding], [padding], [padding-top], [padding-bottom], [padding-start], [padding-end], [padding-vertical], [padding-horizontal], [no-margin], [margin], [margin-top], [margin-bottom], [margin-start], [margin-end], [margin-vertical], [margin-horizontal]',
```
Comment (JMEssex) [inline angular/src/directives/css-utils-deprecations.ts]: Why would you remove `[wrap]` and not remove `[wrap-reverse]` as well?

Comment (brandyscarney) [reply angular/src/directives/css-utils-deprecations.ts]: @JMEssex The `wrap` attribute was only removed from the list of deprecations because it was warning when added to a `textarea` element which is a valid attribute of textarea: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

They will both still be removed as attributes in v5.
